### ISSUE TITLE
Reveiw

### ISSUE THREAD

**Issue by AntonAndell** [icon-community/rewards-distribution-javascore#1]
Instead of stuff like this use context.require: `if (caller.equals(Context.getOwner())) {`
 
 https://github.com/icon-community/rewards-distribution-javascore/blob/4dd29bbdcc780a34231c3a74165f25698fa93f01/smart-contract/contract/src/main/java/contract/Contract.java#L71C11-L71C39 might need to be string i think
 
 
 https://github.com/icon-community/rewards-distribution-javascore/blob/4dd29bbdcc780a34231c3a74165f25698fa93f01/smart-contract/contract/src/main/java/contract/Contract.java#L23 Can be made static aswell so you dont need to pass self

https://github.com/icon-community/rewards-distribution-javascore/blob/4dd29bbdcc780a34231c3a74165f25698fa93f01/smart-contract/contract/src/main/java/contract/Contract.java#L23 Use a dict db instead and you can check admin very fast

https://github.com/icon-community/rewards-distribution-javascore/blob/4dd29bbdcc780a34231c3a74165f25698fa93f01/smart-contract/contract/src/main/java/contract/Contract.java#L122 You could send to the owner instead if you want to add many admins, so that admins can steal funds

**Comment by FidelVe** [comment]
thanks for the review @AntonAndell

**Comment by FidelVe** [comment]
I fixed the smart contract based on recommendations 2 and 4 (made static admins variable and changed logic so that all adminClaim calls will return balance to contract owner not the admin caller)

I have a couple questions regarding the other 2 recommendations:

* about recommendation 1, using Contract.require. My current code works, and one thing I like about the if-else block is that I can define a error message in the else block when calling the Context.revert, what benefit will using Context.require will bring? If I use it I have to remove the if-else block.
* about recommendation 3, changing admins variable from ArrayDB to DictDB, your recommendation about DictDB being faster to search for an admin is it because I can use DictDB.get(adminAddress) and make it return true if the admin exists in the DictDB or false if not? currently with the ArrayDB I simply add the admins to the ArrayDB and then I loop over the array when searching to see if an adminAddress is currently in the array or not

**Comment by AntonAndell** [comment]
Context Require does this automatically and provides simpler code
Context.require(caller.equals(Context.getOwner(), "Only Owner")
so 
Context.require(<Condition>, <Error Message>)

Yeah that's correct just more standard in contracts to avoid iteration but both is fine in this scenario
